import Head from "next/head";
import { useFormik } from "formik";
import * as Yup from "yup";
import { useRouter } from "next/router";
export default function Home() {
  const router = useRouter();
  // formik logic
  const formik = useFormik({
    // here we set the initial values in the form
    initialValues: {
      name: "",
      email: "",
      country: "",
      terms: "",
    },
    // now we add the validation to this
    validationSchema: Yup.object({
      name: Yup.string()
        .max(20, "maximum 20 characters")
        .required("name is reguired"),
      email: Yup.string().email("Invalid email").required("email is reguired"),
      password: Yup.string.max("Enter the password"),
    }),

    // submit the vaues which we inserted
    onSubmit: (values) => {
      console.log(values);
      router.push({ pathname: "/success", query: values });
    },
  });
  console.log(formik.values);
  return (
    <>
      <Head>
        <title>Next Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex items-center justify-center">
        <form
          onSubmit={formik.handleSubmit}
          className="bg-red-500 rounded-lg w-1/2 p-20  "
        >
          <div className=" flex-1">
            <h1 className="text-2xl">Welcome for Registration</h1>
            <p className="mt-10 ">
              In publishing and graphic design, Lorem ipsum is a placeholder
              text commonly used to demonstrate the visual form of a document or
              a typeface without relying on meaningful content.
            </p>
            <div className="mt-5">
              <div className="p-4">
                <label className="block text-sm">
                  {formik.touched.name && formik.errors.name
                    ? formik.errors.name
                    : "Name"}
                </label>
                <input
                  name="name"
                  type="text"
                  placeholder="Enter your Name "
                  className="px-3 pb-2 rounded-md mt-1 text-black focus:text-teal-500 border-2 w-1/2"
                  // these are the values that taked
                  value={formik.values.name}
                  // for to write something in the input field
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                />
              </div>
              <div className="p-4">
                <label className="block text-sm">
                  {formik.touched.email && formik.errors.email
                    ? formik.errors.email
                    : "Email"}
                </label>
                <input
                  name="email"
                  type="email"
                  placeholder="Enter your Name "
                  className="px-3 pb-2 rounded-md mt-1 text-black focus:text-teal-500 border-2 w-1/2"
                  // these are the values that taked
                  value={formik.values.email}
                  // for to write something in the input field
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                />
              </div>
              <div className="p-4">
                <label className="block text-sm">
                  {formik.touched.country && formik.errors.country
                    ? formik.errors.country
                    : "Country"}
                </label>
                <select // these are the values that taked
                  value={formik.values.country}
                  // for to write something in the input field
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                  name="country"
                  className="px-3 pb-2 rounded-md mt-1 text-black focus:text-teal-500 border-2 w-1/2"
                >
                  <option>Pakistan</option>
                  <option>India</option>
                  <option>Bangladesh</option>
                  <option>Germany</option>
                  <option>UK</option>
                </select>
              </div>
              <div className="p-4">
                <label>
                  {formik.touched.terms && formik.errors.terms
                    ? formik.errors.terms
                    : "Terms"}
                </label>
                <p>
                  You have to make sure that you will be sincer to the nation
                  otherwise you got killed by the soviet leader NIKITA
                  KURUSCHEV.
                </p>
                <input
                  type="checkbox"
                  name="terms" // these are the values that taked
                  // for to write something in the input field
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                  value="checked"
                />
              </div>
              <div className="rounded-md p-4 bg-blue-400 text-center cursor-pointer">
                <button type="submit">Submit</button>
              </div>
            </div>
          </div>
        </form>
      </main>
    </>
  );
}
